server:
  port: 8882
# enable all actuator endpoints for testing (review this for real deployments)
management:
  endpoints:
    web:
      exposure:
        include: '*'
spring:
  application:
    name: nacos-consumer
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
